import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const colleges = [
  {
    name: 'Indian Institute of Technology Bombay',
    location: 'Mumbai, Maharashtra',
    state: 'Maharashtra',
    type: 'Public',
    category: 'Engineering',
    fees: 250000,
    rating: 4.8,
    totalRating: 4800,
    reviewCount: 1000,
    established: 1958,
    description: 'IIT Bombay is one of the premier engineering institutions in India, known for world-class research and industry connections.',
    website: 'https://www.iitb.ac.in',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    avgPackage: 22.5,
    maxPackage: 2.2,
    placementRate: 95,
    courses: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'Ph.D', 'B.Des', 'M.Des', 'M.Sc']),
    recruiters: JSON.stringify(['Google', 'Microsoft', 'Goldman Sachs', 'McKinsey', 'Amazon', 'Apple']),
  },
  {
    name: 'Indian Institute of Technology Delhi',
    location: 'New Delhi, Delhi',
    state: 'Delhi',
    type: 'Public',
    category: 'Engineering',
    fees: 220000,
    rating: 4.8,
    totalRating: 4750,
    reviewCount: 980,
    established: 1961,
    description: 'IIT Delhi is a leading technical university in the national capital, renowned for innovation and entrepreneurship.',
    website: 'https://www.iitd.ac.in',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800',
    avgPackage: 21.0,
    maxPackage: 1.8,
    placementRate: 93,
    courses: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'Ph.D', 'M.Sc']),
    recruiters: JSON.stringify(['Google', 'Microsoft', 'Samsung', 'Intel', 'Adobe', 'Oracle']),
  },
  {
    name: 'BITS Pilani',
    location: 'Pilani, Rajasthan',
    state: 'Rajasthan',
    type: 'Deemed',
    category: 'Engineering',
    fees: 520000,
    rating: 4.6,
    totalRating: 4600,
    reviewCount: 1020,
    established: 1964,
    description: 'BITS Pilani is a top private technical university known for its unique dual-degree programs and strong industry practice school.',
    website: 'https://www.bits-pilani.ac.in',
    image: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=800',
    avgPackage: 18.5,
    maxPackage: 1.5,
    placementRate: 90,
    courses: JSON.stringify(['B.E', 'M.E', 'M.Sc', 'Ph.D', 'B.Pharm', 'MBA']),
    recruiters: JSON.stringify(['Microsoft', 'Qualcomm', 'Flipkart', 'Amazon', 'DE Shaw', 'Tower Research']),
  },
  {
    name: 'Indian Institute of Management Ahmedabad',
    location: 'Ahmedabad, Gujarat',
    state: 'Gujarat',
    type: 'Public',
    category: 'Management',
    fees: 2300000,
    rating: 4.9,
    totalRating: 4900,
    reviewCount: 890,
    established: 1961,
    description: 'IIM Ahmedabad is India\'s top business school, consistently ranked among the best management institutes globally.',
    website: 'https://www.iima.ac.in',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    avgPackage: 34.0,
    maxPackage: 7.0,
    placementRate: 100,
    courses: JSON.stringify(['MBA (PGP)', 'MBA (PGPX)', 'Ph.D', 'Executive MBA', 'PGP-FABM']),
    recruiters: JSON.stringify(['McKinsey', 'BCG', 'Bain', 'Goldman Sachs', 'JP Morgan', 'Amazon']),
  },
  {
    name: 'National Law School of India University',
    location: 'Bengaluru, Karnataka',
    state: 'Karnataka',
    type: 'Public',
    category: 'Law',
    fees: 180000,
    rating: 4.7,
    totalRating: 4700,
    reviewCount: 450,
    established: 1987,
    description: 'NLSIU Bangalore is India\'s premier law school and consistently tops the NIRF Law Rankings.',
    website: 'https://www.nls.ac.in',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800',
    avgPackage: 16.0,
    maxPackage: 0.8,
    placementRate: 88,
    courses: JSON.stringify(['B.A. LL.B', 'LL.M', 'Ph.D', 'Executive LL.M']),
    recruiters: JSON.stringify(['AZB Partners', 'Cyril Amarchand', 'Khaitan & Co', 'J Sagar Associates', 'Trilegal']),
  },
  {
    name: 'All India Institute of Medical Sciences Delhi',
    location: 'New Delhi, Delhi',
    state: 'Delhi',
    type: 'Public',
    category: 'Medical',
    fees: 6000,
    rating: 4.9,
    totalRating: 4900,
    reviewCount: 780,
    established: 1956,
    description: 'AIIMS Delhi is India\'s most prestigious medical institution, offering world-class medical education and healthcare.',
    website: 'https://www.aiims.edu',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800',
    avgPackage: 12.0,
    maxPackage: 0.5,
    placementRate: 98,
    courses: JSON.stringify(['MBBS', 'MD', 'MS', 'M.Ch', 'DM', 'Ph.D', 'B.Sc Nursing']),
    recruiters: JSON.stringify(['Apollo Hospitals', 'Fortis Healthcare', 'Max Healthcare', 'AIIMS', 'PGI Chandigarh']),
  },
  {
    name: 'Vellore Institute of Technology',
    location: 'Vellore, Tamil Nadu',
    state: 'Tamil Nadu',
    type: 'Deemed',
    category: 'Engineering',
    fees: 380000,
    rating: 4.2,
    totalRating: 4200,
    reviewCount: 2100,
    established: 1984,
    description: 'VIT is a leading private university known for its international collaborations and strong tech placements.',
    website: 'https://www.vit.ac.in',
    image: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800',
    avgPackage: 7.5,
    maxPackage: 0.8,
    placementRate: 82,
    courses: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'MCA', 'M.Sc', 'Ph.D']),
    recruiters: JSON.stringify(['Wipro', 'TCS', 'Infosys', 'Cognizant', 'Capgemini', 'Accenture']),
  },
  {
    name: 'Symbiosis Institute of Business Management',
    location: 'Pune, Maharashtra',
    state: 'Maharashtra',
    type: 'Deemed',
    category: 'Management',
    fees: 1600000,
    rating: 4.1,
    totalRating: 4100,
    reviewCount: 640,
    established: 1978,
    description: 'SIBM Pune is one of the top private MBA institutes in India, known for its industry interface and global exposure.',
    website: 'https://www.sibmpune.edu.in',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    avgPackage: 14.5,
    maxPackage: 0.9,
    placementRate: 95,
    courses: JSON.stringify(['MBA', 'Executive MBA', 'Ph.D']),
    recruiters: JSON.stringify(['Deloitte', 'EY', 'KPMG', 'HDFC Bank', 'Axis Bank', 'Nestle']),
  },
  {
    name: 'Delhi College of Engineering',
    location: 'New Delhi, Delhi',
    state: 'Delhi',
    type: 'Public',
    category: 'Engineering',
    fees: 125000,
    rating: 4.0,
    totalRating: 4000,
    reviewCount: 1200,
    established: 1941,
    description: 'DCE (now DTU) is one of the oldest and most reputed engineering colleges in North India.',
    website: 'https://www.dtu.ac.in',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    avgPackage: 11.2,
    maxPackage: 0.7,
    placementRate: 80,
    courses: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'Ph.D', 'B.E']),
    recruiters: JSON.stringify(['Amazon', 'Samsung', 'HCL', 'Infosys', 'Walmart Labs', 'Paytm']),
  },
  {
    name: 'Christ University',
    location: 'Bengaluru, Karnataka',
    state: 'Karnataka',
    type: 'Deemed',
    category: 'Arts',
    fees: 195000,
    rating: 4.1,
    totalRating: 4100,
    reviewCount: 1800,
    established: 1969,
    description: 'Christ University is a prestigious institution known for its commerce, arts, and science programs.',
    website: 'https://www.christuniversity.in',
    image: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800',
    avgPackage: 5.8,
    maxPackage: 0.4,
    placementRate: 74,
    courses: JSON.stringify(['B.Com', 'BBA', 'B.Sc', 'BA', 'MBA', 'MCA', 'M.Com', 'Law']),
    recruiters: JSON.stringify(['Deloitte', 'EY', 'KPMG', 'Wipro', 'TCS', 'Infosys']),
  },
  {
    name: 'Manipal Institute of Technology',
    location: 'Manipal, Karnataka',
    state: 'Karnataka',
    type: 'Deemed',
    category: 'Engineering',
    fees: 420000,
    rating: 4.2,
    totalRating: 4200,
    reviewCount: 1560,
    established: 1957,
    description: 'MIT Manipal is a leading private engineering college known for its diverse student body and excellent infrastructure.',
    website: 'https://www.manipal.edu',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
    avgPackage: 8.2,
    maxPackage: 0.6,
    placementRate: 79,
    courses: JSON.stringify(['B.Tech', 'M.Tech', 'MBA', 'MCA', 'Ph.D']),
    recruiters: JSON.stringify(['Infosys', 'TCS', 'Wipro', 'Cognizant', 'Oracle', 'IBM']),
  },
  {
    name: 'Jadavpur University',
    location: 'Kolkata, West Bengal',
    state: 'West Bengal',
    type: 'Public',
    category: 'Engineering',
    fees: 50000,
    rating: 4.4,
    totalRating: 4400,
    reviewCount: 920,
    established: 1955,
    description: 'Jadavpur University is a top public university in Eastern India, known for research excellence and strong alumni network.',
    website: 'https://www.jaduniv.edu.in',
    image: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800',
    avgPackage: 9.5,
    maxPackage: 0.6,
    placementRate: 83,
    courses: JSON.stringify(['B.E', 'M.E', 'B.Tech', 'M.Tech', 'BA', 'MA', 'Ph.D', 'M.Sc']),
    recruiters: JSON.stringify(['TCS', 'Infosys', 'Wipro', 'HCL', 'Capgemini', 'IBM']),
  },
];

async function main() {
  console.log('Seeding database...');
  await prisma.college.deleteMany();
  for (const college of colleges) {
    await prisma.college.create({ data: college });
  }
  console.log(`Seeded ${colleges.length} colleges.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
